#!/bin/sh

#
# Author: C. R. Zamana (czamana at gmail dot com)
#
# PROVIDE: flaresolverr
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="flaresolverr"
rcvar="${name}_enable"
load_rc_config ${name}

: ${flaresolverr_enable:="NO"}

pidfile="/var/run/flaresolverr.pid"

start_precmd="flaresolverr_precmd"

PATH=$PATH:/usr/local/bin

flaresolverr_precmd() {
	cd /usr/local/share/FlareSolverr
	export PUPPETEER_EXECUTABLE_PATH=/usr/local/bin/chrome
	export HOST=0.0.0.0
}

command="/usr/sbin/daemon"
command_args="-P ${pidfile} /usr/local/bin/npm start > /dev/null"

run_rc_command "$1"